modLoader="javafml"
loaderVersion="[46,)"
license="MIT License"

[[mods]]
modId="custom_menu_message"
version="1.20.1-0.0"
displayName="Custom Menu Message"
authors="Matt√©o"
description="This mod allow you to replace or add more custom title messages"
logoFile="logo.png"

[[dependencies.custom_menu_message]]
modId="forge"
versionRange="[47.1.0,)"
mandatory=true
side="BOTH"

[[dependencies.custom_menu_message]]
modId="minecraft"
versionRange="1.20.1"
mandatory=true
side="BOTH"